// import mongoose from "mongoose";
// // import mongooseSequence from "mongoose-sequence"

// const userschema = mongoose.Schema({
//   name: String,
//   username: String,
//   email: String,
//   phone: String,
//   myId: Number, // add a field to store the ID generated by mongoose-sequence
// });

// // define a function to generate the sequence
// // const generateSequence = mongooseSequence(mongoose);

// // // attach the sequence generator to the schema
// // userschema.plugin(generateSequence, {inc_field: 'myId'});

// const user = mongoose.model('user',userschema);

// export default user;


import mongoose from 'mongoose';
import autoIncrement from 'mongoose-auto-increment';

// how our document look like
const userSchema = mongoose.Schema({
    name: String,
    username: String,
    email: String,
    phone: Number
});

autoIncrement.initialize(mongoose.connection);
userSchema.plugin(autoIncrement.plugin, {model:'user',startAt: 0});
// we need to turn it into a model
const user = mongoose.model('user', userSchema);

export default user;